name: Deploy Azure Functions

on:
  push:
    tags:
      - 'v-*'  # Trigger on any tag starting with v-
  workflow_dispatch:  # Allow manual triggering

permissions:
  id-token: write  # Required for OIDC auth
  contents: read

env:
  PYTHON_VERSION: '3.11'

jobs:
  deploy:
    name: Deploy Azure Function
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed for tag history

      - name: Extract tag info
        id: tag-info
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          FUNCTION_ID=$(echo $TAG_NAME | cut -d'-' -f2-)
          echo "function_id=$FUNCTION_ID" >> $GITHUB_OUTPUT
          echo "Extracted tag name: $TAG_NAME"
          echo "Extracted function ID: $FUNCTION_ID"

      # No conditional check here - this will always run
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Path is now hardcoded to your delete-api function
      - name: Install dependencies
        run: |
          if [ -f "src/delete-api/requirements.txt" ]; then
            pip install -r delete-api/requirements.txt
          elif [ -f "delete-api/requirements.txt" ]; then
            pip install -r delete-api/requirements.txt
          fi

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Function
        uses: azure/functions-action@v1
        with:
          app-name: "delete-api"
          package: "delete-api"  # Adjust this path if needed based on your repo structure